"""
CornScan AI · data/disease_info.py
All static data: CLASSES, DISEASE_INFO, WEATHER_CONDITIONS
"""

CLASSES = ["Blight", "Common Rust", "Gray Leaf Spot", "Healthy"]

DISEASE_INFO = {
    "Blight": {
        "icon": "🍂", "severity": "HIGH", "sev_color": "#ff5757",
        "short": "Northern Corn Leaf Blight",
        "pathogen": "Exserohilum turcicum",
        "description": "A serious fungal disease thriving in moderate temperatures (18–27°C) with extended leaf-wetness. Can reduce yield by 30–50% in epidemic years.",
        "action": "Apply strobilurin fungicide at early tassel. Remove infected residue post-harvest.",
        "symptoms": ["Cigar-shaped grey-green lesions (3–15 cm)", "Tan-brown mature lesions", "Olive spore masses on leaf surface"],
        "urgency": "HIGH",
        "treatment": [
            "Immediate fungicide application (strobilurin class)",
            "Remove and destroy heavily infected leaves",
            "Increase row spacing for airflow",
            "Monitor surrounding plants weekly"
        ],
        "farmer_advice": "Rotate crops with non-host species. Scout fields after prolonged wet periods. Ensure adequate plant spacing to reduce canopy humidity. Consider resistant hybrid varieties for next season.",
        "expert_note": "E. turcicum overwinters in infected crop debris. Spores (conidia) are dispersed by wind and rain splash. Race 0 is most common; races 1, 2, 3 overcome Ht-gene resistance.",
        "weather_trigger": "Cool, wet weather (18–27°C, RH>80%) dramatically increases infection risk.",
        "plan_3day": ["Day 1: Apply Azoxystrobin 25WP at 1g/L", "Day 2: Remove necrotic tissue, bag and destroy", "Day 3: Scout 50 plants, document lesion count"],
        "plan_7day": ["Days 1–2: Fungicide + debris removal", "Days 3–4: Increase plant spacing where possible", "Days 5–6: Second scout + weather monitoring", "Day 7: Follow-up spray if RH stays >80%"],
        "prevention": ["Plant Ht-gene resistant hybrids", "Rotate with soybean or wheat", "Deep-tillage to bury infected residue", "Avoid overhead irrigation"],
        "risk_score": 82,
        "yield_impact": "30–50%",
        "spread_rate": "Rapid",
    },
    "Common Rust": {
        "icon": "🟠", "severity": "MEDIUM", "sev_color": "#ffb347",
        "short": "Common Corn Rust",
        "pathogen": "Puccinia sorghi",
        "description": "Spreads via airborne spores in cool, humid conditions (16–23°C). Can reduce grain fill by up to 20% with severe pre-silking infection.",
        "action": "Scout weekly from V6. Apply fungicide if >50 pustules per leaf pre-silk.",
        "symptoms": ["Brick-red circular pustules on both surfaces", "Powdery cinnamon-brown spore masses", "Dark brown-black pustules late season"],
        "urgency": "MEDIUM",
        "treatment": [
            "Scout field for pustule density (>50/leaf = treat)",
            "Apply triazole fungicide if threshold exceeded",
            "Track spore forecasts in your region",
            "Record infection spread weekly"
        ],
        "farmer_advice": "Monitor pustule counts weekly. Spores travel long distances by wind. Early-season infections are most damaging. Scout from V6 stage.",
        "expert_note": "P. sorghi is an obligate biotroph with a complex host-alternation cycle (Oxalis spp. as alternate host). Urediniospores are the primary infection cycle in corn fields.",
        "weather_trigger": "Cool nights (16–23°C) with morning dew or fog greatly accelerate spore germination.",
        "plan_3day": ["Day 1: Count pustules on 10 leaves per zone", "Day 2: Apply Propiconazole 25EC if threshold met", "Day 3: Note weather forecast, flag high-density zones"],
        "plan_7day": ["Days 1–2: Threshold scouting + fungicide", "Days 3–4: Monitor new pustule formation", "Days 5–6: Evaluate fungicide efficacy", "Day 7: Decide on second application"],
        "prevention": ["Plant rust-resistant hybrids (Rp1 locus)", "Avoid dense planting", "Monitor regional spore forecasts", "Scout from V4 in high-risk years"],
        "risk_score": 52,
        "yield_impact": "Up to 20%",
        "spread_rate": "Moderate",
    },
    "Gray Leaf Spot": {
        "icon": "🩶", "severity": "HIGH", "sev_color": "#ff5757",
        "short": "Gray Leaf Spot",
        "pathogen": "Cercospora zeae-maydis",
        "description": "Among the most economically damaging corn diseases globally. Overwinters in residue; epidemic in warm, humid, no-till continuous-corn systems.",
        "action": "Plant resistant hybrids. Apply triazole + strobilurin mix at VT/R1.",
        "symptoms": ["Rectangular lesions bounded by leaf veins", "Ash-grey to pale tan colour", "Yellow halo around mature lesions"],
        "urgency": "HIGH",
        "treatment": [
            "Apply triazole + strobilurin combination fungicide",
            "Incorporate infected residue by tillage",
            "Switch to resistant varieties next season",
            "Avoid evening irrigation"
        ],
        "farmer_advice": "Tillage reduces inoculum in infected residue. Avoid continuous corn planting. Irrigate early in the day to reduce overnight leaf wetness.",
        "expert_note": "Two races exist: Type I (C. zeae-maydis) and Type II (C. zeina). Type II shows shorter, narrower lesions and is more prevalent in highland tropical regions.",
        "weather_trigger": "Warm, humid nights (>20°C, RH>90%) combined with dense canopy create epidemic conditions.",
        "plan_3day": ["Day 1: Apply Trifloxystrobin+Propiconazole mix", "Day 2: Begin tillage of infected lower canopy", "Day 3: Adjust irrigation timing to morning only"],
        "plan_7day": ["Days 1–2: Fungicide + canopy management", "Days 3–4: Soil incorporation of residue", "Days 5–6: Upper canopy monitoring", "Day 7: Assess lesion progression rate"],
        "prevention": ["No-till avoidance in continuous corn", "Resistant hybrid selection", "Wider row spacing", "Morning-only irrigation schedule"],
        "risk_score": 78,
        "yield_impact": "Up to 40%",
        "spread_rate": "Rapid",
    },
    "Healthy": {
        "icon": "✅", "severity": "NONE", "sev_color": "#4ade80",
        "short": "No Disease Detected",
        "pathogen": "Zea mays — clean",
        "description": "No signs of fungal, bacterial, or viral disease detected. The leaf appears vigorous with uniform colour and clean surface texture.",
        "action": "Continue routine weekly scouting. Maintain balanced NPK fertilisation.",
        "symptoms": ["Uniform deep-green colour", "Clean surface, no lesions", "Normal venation and architecture"],
        "urgency": "NONE",
        "treatment": [
            "Continue regular scouting schedule",
            "Maintain balanced fertilizer program",
            "Monitor weather forecasts",
            "Document healthy baseline for comparison"
        ],
        "farmer_advice": "Excellent leaf health. Maintain soil moisture, ensure micronutrient availability (Zn, Mn), and continue integrated pest management protocols.",
        "expert_note": "Healthy corn at vegetative stages should show SPAD readings of 45–55. Chlorophyll content index (CCI) above 35 typically indicates adequate N nutrition.",
        "weather_trigger": "Current conditions appear favourable. Monitor forecasts for upcoming wet or humid periods.",
        "plan_3day": ["Day 1: Soil moisture check + NDVI reading", "Day 2: Micronutrient foliar if Zn/Mn deficiency suspected", "Day 3: Weather forecast review"],
        "plan_7day": ["Days 1–3: Baseline documentation", "Days 4–5: Fertilizer program review", "Days 6–7: Next-cycle variety planning"],
        "prevention": ["Maintain IPM protocols", "Regular field scouting", "Balanced NPK program", "Crop rotation planning"],
        "risk_score": 8,
        "yield_impact": "None",
        "spread_rate": "N/A",
    },
    "GrayLeafSpot": {
        "icon": "🩶", "severity": "HIGH", "sev_color": "#ff5757",
        "short": "Gray Leaf Spot",
        "pathogen": "Cercospora zeae-maydis",
        "description": "Among the most economically damaging corn diseases globally. Overwinters in residue; epidemic in warm, humid, no-till continuous-corn systems.",
        "action": "Plant resistant hybrids. Apply triazole + strobilurin mix at VT/R1.",
        "symptoms": ["Rectangular lesions bounded by leaf veins", "Ash-grey to pale tan colour", "Yellow halo around mature lesions"],
        "urgency": "HIGH",
        "treatment": [
            "Apply triazole + strobilurin combination fungicide",
            "Incorporate infected residue by tillage",
            "Switch to resistant varieties next season",
            "Avoid evening irrigation"
        ],
        "farmer_advice": "Tillage reduces inoculum in infected residue. Avoid continuous corn planting. Irrigate early in the day to reduce overnight leaf wetness.",
        "expert_note": "Two races exist: Type I (C. zeae-maydis) and Type II (C. zeina). Type II shows shorter, narrower lesions and is more prevalent in highland tropical regions.",
        "weather_trigger": "Warm, humid nights (>20°C, RH>90%) combined with dense canopy create epidemic conditions.",
        "plan_3day": ["Day 1: Apply Trifloxystrobin+Propiconazole mix", "Day 2: Begin tillage of infected lower canopy", "Day 3: Adjust irrigation timing to morning only"],
        "plan_7day": ["Days 1–2: Fungicide + canopy management", "Days 3–4: Soil incorporation of residue", "Days 5–6: Upper canopy monitoring", "Day 7: Assess lesion progression rate"],
        "prevention": ["No-till avoidance in continuous corn", "Resistant hybrid selection", "Wider row spacing", "Morning-only irrigation schedule"],
        "risk_score": 78,
        "yield_impact": "Up to 40%",
        "spread_rate": "Rapid",
    },
    "Rust": {
        "icon": "🟠", "severity": "MEDIUM", "sev_color": "#ffb347",
        "short": "Common Corn Rust",
        "pathogen": "Puccinia sorghi",
        "description": "Spreads via airborne spores in cool, humid conditions (16–23°C). Can reduce grain fill by up to 20% with severe pre-silking infection.",
        "action": "Scout weekly from V6. Apply fungicide if >50 pustules per leaf pre-silk.",
        "symptoms": ["Brick-red circular pustules on both surfaces", "Powdery cinnamon-brown spore masses", "Dark brown-black pustules late season"],
        "urgency": "MEDIUM",
        "treatment": [
            "Scout field for pustule density (>50/leaf = treat)",
            "Apply triazole fungicide if threshold exceeded",
            "Track spore forecasts in your region",
            "Record infection spread weekly"
        ],
        "farmer_advice": "Monitor pustule counts weekly. Spores travel long distances by wind. Early-season infections are most damaging. Scout from V6 stage.",
        "expert_note": "P. sorghi is an obligate biotroph with a complex host-alternation cycle (Oxalis spp. as alternate host). Urediniospores are the primary infection cycle in corn fields.",
        "weather_trigger": "Cool nights (16–23°C) with morning dew or fog greatly accelerate spore germination.",
        "plan_3day": ["Day 1: Count pustules on 10 leaves per zone", "Day 2: Apply Propiconazole 25EC if threshold met", "Day 3: Note weather forecast, flag high-density zones"],
        "plan_7day": ["Days 1–2: Threshold scouting + fungicide", "Days 3–4: Monitor new pustule formation", "Days 5–6: Evaluate fungicide efficacy", "Day 7: Decide on second application"],
        "prevention": ["Plant rust-resistant hybrids (Rp1 locus)", "Avoid dense planting", "Monitor regional spore forecasts", "Scout from V4 in high-risk years"],
        "risk_score": 52,
        "yield_impact": "Up to 20%",
        "spread_rate": "Moderate",
    },
}

WEATHER_CONDITIONS = [
    {"label": "Hot & Dry",    "icon": "☀️",  "risk": "LOW",    "risk_pct": 18, "risk_color": "#4ade80", "desc": "Low humidity suppresses fungal spore germination. Monitor for heat stress."},
    {"label": "Warm & Humid", "icon": "🌤️", "risk": "MEDIUM", "risk_pct": 55, "risk_color": "#ffb347", "desc": "Moderate conditions favour rust development. Increase scouting frequency."},
    {"label": "Cool & Wet",   "icon": "🌧️", "risk": "HIGH",   "risk_pct": 82, "risk_color": "#ff5757", "desc": "Ideal conditions for blight and gray leaf spot. Consider preventive fungicide."},
    {"label": "Foggy & Mild", "icon": "🌫️", "risk": "HIGH",   "risk_pct": 76, "risk_color": "#ff5757", "desc": "Extended leaf wetness from fog greatly accelerates all fungal diseases."},
]
